Foreground true
TCPSocket 3310
TCPAddr 127.0.0.1
LocalSocket /run/clamav/clamd.ctl
User clamav
MaxFileSize 12M
MaxScanSize 12M
StreamMaxLength 12M
LogTime true
LogClean false
LogSyslog false
DatabaseDirectory /var/lib/clamav
